### ISSUE TITLE
Feedback on README

### ISSUE THREAD

**Issue by consideRatio** [synvinkel/mtf-sat-doc#1]
Thank you for providing information about this exciting API!

After my read through of the README, I was left with the following questions:

1. What does MTF stand for?
2. How do I get an API key?
3. How do you run the example?

Regarding how to run example code, mybinder.org can help out quite often. For the end user it will be as simple as a by the click of a button to enter the environment where code can be executed:

[![Binder](https://mybinder.org/badge_logo.svg)](https://beta.mybinder.org/v2/gh/minrk/ligo-binder/master?urlpath=/lab/tree/index.ipynb)

For instructions on how to make a github repo mybinder.org compatible, see:
https://mybinder.readthedocs.io/en/latest/introduction.html

There is also a lot of example repositories:
https://mybinder.readthedocs.io/en/latest/sample_repos.html

This image summarize the MyBinder.org experience to some degree:
[![image](https://user-images.githubusercontent.com/3837114/55411711-6d487100-5566-11e9-9434-05e8741a1fb4.png)](https://twitter.com/mybinderteam/status/1082556317842264064) _@JulietteTaka on Twitter_

I'm happy to have learned about this API! :heart:

**Comment by TobiasEdman** [comment]
Hi,

1. MTF stands for music tech fest

2. You get the api key by asking at the hackforsweden slack post

3. You past them inthe navigation bar of your browser.

Tobias

2 apr. 2019 kl. 16:44 skrev Erik Sundell <notifications@github.com<mailto:notifications@github.com>>:


Thank you for providing information about this exciting API!

After my read through of the README, I was left with the following questions:

  1.  What does MTF stand for?
  2.  How do I get an API key?
  3.  How do you run the example?

Regarding how to run example code, mybinder.org<http://mybinder.org> can help out quite often. For the end user it will be as simple as a by the click of a button to enter the environment where code can be executed:

[Binder]<https://beta.mybinder.org/v2/gh/minrk/ligo-binder/master?urlpath=/lab/tree/index.ipynb>

For instructions on how to make a github repo mybinder.org<http://mybinder.org> compatible, see:
https://mybinder.readthedocs.io/en/latest/introduction.html

There is also a lot of example repositories:
https://mybinder.readthedocs.io/en/latest/sample_repos.html

This image summarize the MyBinder.org<http://MyBinder.org> experience to some degree:
[image]<https://user-images.githubusercontent.com/3837114/55411711-6d487100-5566-11e9-9434-05e8741a1fb4.png>

I'm happy to have learned about this API! ❤️

**Comment by johnniehard** [comment]
Binder is an excellent idea! I won't be able to set that up right now though, feel free to submit a pull request if you feel inclined to set it up.

For now I would go with either (1) simply pasting the examples into the address bar of your browser, (2) curl or wget, or (3) running and modifying the example script.

Closing this as I think @TobiasEdman provided good answers. Feel free to open if you have further questions.
